from __future__ import annotations

import json
import re
from pathlib import Path


NEXT_VERSION_FILENAME = "VERSION_NEXT"
BUILD_VERSION_MODULE = Path("difftrail/_build_version.py")
TAURI_BUILD_CONFIG = Path("ui/src-tauri/tauri.build.conf.json")
SHORT_SHA_LENGTH = 7

_STABLE_VERSION_PATTERN = re.compile(
    r"^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$"
)
_DEVELOPMENT_VERSION_PATTERN = re.compile(
    r"^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)"
    r"-dev\.[1-9]\d*\+[0-9A-Za-z-]+$"
)
_COMMIT_SHA_PATTERN = re.compile(r"^[0-9a-fA-F]+$")
_PR_NUMBER_PATTERN = re.compile(r"^[1-9]\d*$")


def validate_stable_version(version: str) -> str:
    """Return a plain SemVer release version or reject it."""

    candidate = version.strip()
    if not _STABLE_VERSION_PATTERN.fullmatch(candidate):
        raise ValueError(
            f"Next version must be a plain MAJOR.MINOR.PATCH version, got {version!r}"
        )
    return candidate


def read_next_version(root: Path) -> str:
    """Read and validate the release version currently under development."""

    path = root / NEXT_VERSION_FILENAME
    lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if len(lines) != 1:
        raise ValueError(f"{NEXT_VERSION_FILENAME} must contain exactly one version line")
    return validate_stable_version(lines[0])


def short_commit_sha(commit_sha: str) -> str:
    """Return the seven-character commit identity used in build labels."""

    candidate = commit_sha.strip()
    if len(candidate) < SHORT_SHA_LENGTH or not _COMMIT_SHA_PATTERN.fullmatch(candidate):
        raise ValueError("Commit SHA must contain at least seven hexadecimal characters")
    return candidate[:SHORT_SHA_LENGTH].lower()


def validate_pull_request_number(pr_number: str | int) -> str:
    """Return a normalized positive pull-request number."""

    candidate = str(pr_number).strip()
    if not _PR_NUMBER_PATTERN.fullmatch(candidate):
        raise ValueError(f"Pull-request number must be positive, got {pr_number!r}")
    return candidate


def development_version(next_version: str, pr_number: str | int, commit_sha: str) -> str:
    """Build the disposable SemVer used by pull-request installers."""

    base = validate_stable_version(next_version)
    pull_request = validate_pull_request_number(pr_number)
    return f"{base}-dev.{pull_request}+{short_commit_sha(commit_sha)}"


def artifact_name(pr_number: str | int, commit_sha: str) -> str:
    """Return an unambiguous CI artifact name for a pull-request build."""

    return f"difftrail-windows-installer-pr-{validate_pull_request_number(pr_number)}-{short_commit_sha(commit_sha)}"


def write_build_stamp(root: Path, version: str) -> None:
    """Write ignored build-only inputs consumed by the backend and Tauri."""

    if _DEVELOPMENT_VERSION_PATTERN.fullmatch(version) is None:
        raise ValueError(f"Invalid disposable build version: {version!r}")

    build_module = root / BUILD_VERSION_MODULE
    build_module.parent.mkdir(parents=True, exist_ok=True)
    build_module.write_text(
        "\n".join(
            (
                '"""Disposable build version generated by CI; do not commit."""',
                "",
                f"BUILD_VERSION = {version!r}",
                "",
            )
        ),
        encoding="utf-8",
    )

    tauri_config = root / TAURI_BUILD_CONFIG
    tauri_config.parent.mkdir(parents=True, exist_ok=True)
    tauri_config.write_text(
        json.dumps({"version": version}, indent=2) + "\n",
        encoding="utf-8",
    )
